// Every monster in src/monst.c, in its order: [name, class symbol, colour (CLR_* index)].
// Generated from the game source; monster-roster.test.js checks that it still matches.
export const MONSTERS=[["giant ant", "a", 3],
["killer bee", "a", 11],
["soldier ant", "a", 4],
["fire ant", "a", 1],
["snow ant", "a", 6],
["giant beetle", "a", 0],
["queen bee", "a", 5],
["locust", "a", 7],
["acid blob", "b", 2],
["quivering blob", "b", 15],
["gelatinous cube", "b", 6],
["chickatrice", "c", 3],
["cockatrice", "c", 11],
["pyrolisk", "c", 1],
["jackal", "d", 3],
["fox", "d", 1],
["coyote", "d", 3],
["werejackal", "d", 5],
["little dog", "d", 15],
["dog", "d", 15],
["large dog", "d", 15],
["dingo", "d", 11],
["wolf", "d", 7],
["werewolf", "d", 5],
["warg", "d", 0],
["winter wolf cub", "d", 6],
["winter wolf", "d", 6],
["hell hound pup", "d", 1],
["hell hound", "d", 1],
["Cerberus", "d", 1],
["gas spore", "e", 7],
["floating eye", "e", 10],
["freezing sphere", "e", 15],
["flaming sphere", "e", 1],
["shocking sphere", "e", 12],
["evil eye", "e", 13],
["beholder", "e", 3],
["kitten", "f", 15],
["housecat", "f", 15],
["jaguar", "f", 3],
["lynx", "f", 6],
["panther", "f", 0],
["large cat", "f", 15],
["tiger", "f", 11],
["gremlin", "g", 2],
["gargoyle", "g", 3],
["winged gargoyle", "g", 5],
["hobbit", "h", 2],
["dwarf", "h", 1],
["bugbear", "h", 3],
["dwarf lord", "h", 4],
["dwarf king", "h", 5],
["mind flayer", "h", 13],
["master mind flayer", "h", 13],
["manes", "i", 1],
["homunculus", "i", 2],
["imp", "i", 1],
["lemure", "i", 3],
["quasit", "i", 4],
["tengu", "i", 6],
["uranium imp", "i", 10],
["blue jelly", "j", 4],
["spotted jelly", "j", 2],
["ochre jelly", "j", 3],
["kobold", "k", 3],
["large kobold", "k", 1],
["kobold lord", "k", 5],
["kobold shaman", "k", 12],
["leprechaun", "l", 2],
["small mimic", "m", 3],
["large mimic", "m", 1],
["giant mimic", "m", 5],
["wood nymph", "n", 2],
["water nymph", "n", 4],
["mountain nymph", "n", 3],
["Aphrodite", "n", 5],
["goblin", "o", 7],
["hobgoblin", "o", 3],
["orc", "o", 1],
["hill orc", "o", 11],
["Mordor orc", "o", 4],
["Uruk-hai", "o", 0],
["orc shaman", "o", 12],
["orc-captain", "o", 5],
["deep orc", "o", 2],
["rock piercer", "p", 7],
["iron piercer", "p", 6],
["glass piercer", "p", 15],
["rothe", "q", 3],
["mumak", "q", 7],
["leocrotta", "q", 1],
["wumpus", "q", 6],
["titanothere", "q", 7],
["baluchitherium", "q", 7],
["mastodon", "q", 0],
["sewer rat", "r", 3],
["giant rat", "r", 3],
["rabid rat", "r", 3],
["wererat", "r", 5],
["enormous rat", "r", 3],
["rock mole", "r", 7],
["woodchuck", "r", 3],
["cave spider", "s", 7],
["centipede", "s", 11],
["giant spider", "s", 5],
["scorpion", "s", 1],
["lurker above", "t", 7],
["trapper", "t", 2],
["white unicorn", "u", 15],
["gray unicorn", "u", 7],
["black unicorn", "u", 0],
["pony", "u", 3],
["horse", "u", 3],
["warhorse", "u", 3],
["fog cloud", "v", 7],
["dust vortex", "v", 3],
["ice vortex", "v", 6],
["energy vortex", "v", 12],
["steam vortex", "v", 4],
["fire vortex", "v", 11],
["baby long worm", "w", 3],
["baby purple worm", "w", 5],
["long worm", "w", 3],
["purple worm", "w", 5],
["grid bug", "x", 5],
["xan", "x", 1],
["chillbug", "x", 12],
["yellow light", "y", 11],
["black light", "y", 0],
["zruty", "z", 3],
["couatl", "A", 2],
["Aleax", "A", 9],
["Angel", "A", 15],
["dark Angel", "A", 0],
["ki-rin", "A", 11],
["Archon", "A", 5],
["weeping angel", "A", 7],
["weeping archangel", "A", 13],
["bat", "B", 3],
["giant bat", "B", 1],
["raven", "B", 0],
["vampire bat", "B", 0],
["plains centaur", "C", 3],
["forest centaur", "C", 2],
["mountain centaur", "C", 6],
["baby tatzelworm", "D", 3],
["baby amphitere", "D", 3],
["baby shimmering dragon", "D", 6],
["baby draken", "D", 3],
["baby lindworm", "D", 3],
["baby sarkany", "D", 3],
["baby sirrush", "D", 3],
["baby leviathan", "D", 3],
["baby wyvern", "D", 3],
["baby glowing dragon", "D", 3],
["baby guivre", "D", 3],
["tatzelworm", "D", 3],
["amphitere", "D", 3],
["shimmering dragon", "D", 6],
["draken", "D", 3],
["lindworm", "D", 3],
["sarkany", "D", 3],
["sirrush", "D", 3],
["leviathan", "D", 3],
["wyvern", "D", 3],
["glowing dragon", "D", 3],
["guivre", "D", 3],
["chromatic dragon", "D", 5],
["stalker", "E", 15],
["air elemental", "E", 6],
["fire elemental", "E", 11],
["earth elemental", "E", 3],
["water elemental", "E", 4],
["lichen", "F", 10],
["brown mold", "F", 3],
["yellow mold", "F", 11],
["green mold", "F", 2],
["red mold", "F", 1],
["shrieker", "F", 5],
["violet fungus", "F", 5],
["gnome", "G", 3],
["gnome lord", "G", 4],
["gnomish wizard", "G", 12],
["gnome king", "G", 5],
["giant", "H", 1],
["stone giant", "H", 7],
["hill giant", "H", 6],
["fire giant", "H", 11],
["frost giant", "H", 15],
["storm giant", "H", 4],
["ettin", "H", 3],
["titan", "H", 5],
["minotaur", "H", 3],
["jabberwock", "J", 9],
["vorpal jabberwock", "J", 5],
["Keystone Kop", "K", 4],
["Kop Sergeant", "K", 4],
["Kop Lieutenant", "K", 6],
["Kop Kaptain", "K", 5],
["lich", "L", 3],
["demilich", "L", 1],
["master lich", "L", 5],
["arch-lich", "L", 13],
["kobold mummy", "M", 3],
["gnome mummy", "M", 1],
["orc mummy", "M", 7],
["dwarf mummy", "M", 1],
["elf mummy", "M", 2],
["human mummy", "M", 7],
["ettin mummy", "M", 4],
["giant mummy", "M", 6],
["red naga hatchling", "N", 1],
["black naga hatchling", "N", 0],
["golden naga hatchling", "N", 11],
["guardian naga hatchling", "N", 2],
["white naga hatchling", "N", 15],
["red naga", "N", 1],
["black naga", "N", 0],
["golden naga", "N", 11],
["guardian naga", "N", 2],
["white naga", "N", 15],
["ogre", "O", 3],
["ogre lord", "O", 1],
["ogre king", "O", 5],
["gray ooze", "P", 7],
["brown pudding", "P", 3],
["black pudding", "P", 0],
["green slime", "P", 2],
["blue slime", "P", 12],
["quantum mechanic", "Q", 6],
["rust monster", "R", 3],
["disenchanter", "R", 4],
["disintegrator", "R", 10],
["garter snake", "S", 2],
["snake", "S", 3],
["water moccasin", "S", 1],
["pit viper", "S", 4],
["python", "S", 5],
["cobra", "S", 4],
["troll", "T", 3],
["ice troll", "T", 15],
["rock troll", "T", 6],
["water troll", "T", 4],
["Olog-hai", "T", 5],
["umber hulk", "U", 3],
["shambling horror", "U", 14],
["vampire", "V", 1],
["vampire lord", "V", 4],
["vampire mage", "V", 12],
["Vlad the Impaler", "V", 5],
["barrow wight", "W", 7],
["wraith", "W", 0],
["Nazgul", "W", 5],
["xorn", "X", 3],
["monkey", "Y", 7],
["ape", "Y", 3],
["owlbear", "Y", 3],
["yeti", "Y", 15],
["carnivorous ape", "Y", 0],
["sasquatch", "Y", 7],
["kobold zombie", "Z", 3],
["gnome zombie", "Z", 3],
["orc zombie", "Z", 7],
["dwarf zombie", "Z", 1],
["elf zombie", "Z", 2],
["human zombie", "Z", 15],
["ettin zombie", "Z", 4],
["giant zombie", "Z", 6],
["ghoul", "Z", 0],
["skeleton", "Z", 15],
["straw golem", "'", 11],
["paper golem", "'", 15],
["wax golem", "'", 7],
["rope golem", "'", 3],
["gold golem", "'", 11],
["leather golem", "'", 3],
["wood golem", "'", 3],
["flesh golem", "'", 1],
["clay golem", "'", 3],
["stone golem", "'", 7],
["glass golem", "'", 6],
["iron golem", "'", 6],
["ice golem", "'", 14],
["crystal ice golem", "'", 12],
["human", "@", 15],
["miner", "@", 7],
["prison guard", "@", 6],
["wererat", "@", 3],
["werejackal", "@", 1],
["werewolf", "@", 9],
["elf", "@", 15],
["Woodland-elf", "@", 2],
["Green-elf", "@", 10],
["Grey-elf", "@", 7],
["elf-lord", "@", 12],
["Elvenking", "@", 5],
["doppelganger", "@", 15],
["mugger", "@", 0],
["nurse", "@", 15],
["shopkeeper", "@", 11],
["black marketeer", "@", 11],
["One-eyed Sam", "@", 0],
["guard", "@", 4],
["prisoner", "@", 15],
["Oracle", "@", 12],
["aligned priest", "@", 15],
["high priest", "@", 15],
["soldier", "@", 7],
["sergeant", "@", 1],
["lieutenant", "@", 2],
["captain", "@", 4],
["watchman", "@", 7],
["watch captain", "@", 2],
["Medusa", "@", 10],
["Wizard of Yendor", "@", 13],
["Croesus", "@", 5],
["Executioner", "@", 5],
["Charon", "@", 15],
["ghost", " ", 7],
["shade", " ", 0],
["water demon", "&", 4],
["lava demon", "&", 1],
["horned devil", "&", 3],
["succubus", "&", 7],
["incubus", "&", 7],
["erinys", "&", 1],
["barbed devil", "&", 1],
["marilith", "&", 1],
["vrock", "&", 2],
["hezrou", "&", 2],
["bone devil", "&", 7],
["ice devil", "&", 15],
["nalfeshnee", "&", 1],
["pit fiend", "&", 1],
["balrog", "&", 1],
["Juiblex", "&", 10],
["Yeenoghu", "&", 5],
["Orcus", "&", 5],
["Geryon", "&", 5],
["Dispater", "&", 5],
["Baalzebub", "&", 5],
["Asmodeus", "&", 5],
["Demogorgon", "&", 5],
["Cthulhu", "h", 10],
["Death", "&", 13],
["Pestilence", "&", 13],
["Famine", "&", 13],
["mail daemon", "&", 12],
["djinni", "&", 11],
["sandestin", "&", 7],
["jellyfish", ";", 4],
["piranha", ";", 1],
["shark", ";", 7],
["giant eel", ";", 6],
["electric eel", ";", 12],
["kraken", ";", 1],
["newt", ":", 11],
["gecko", ":", 2],
["iguana", ":", 3],
["baby crocodile", ":", 3],
["giant turtle", ":", 10],
["lizard", ":", 2],
["chameleon", ":", 3],
["crocodile", ":", 3],
["salamander", ":", 9],
["long worm tail", "~", 3],
["archeologist", "@", 15],
["barbarian", "@", 15],
["caveman", "@", 15],
["cavewoman", "@", 15],
["convict", "@", 15],
["healer", "@", 15],
["knight", "@", 15],
["monk", "@", 15],
["priest", "@", 15],
["priestess", "@", 15],
["ranger", "@", 15],
["rogue", "@", 15],
["samurai", "@", 15],
["tourist", "@", 15],
["valkyrie", "@", 15],
["wizard", "@", 15],
["Lord Carnarvon", "@", 5],
["Pelias", "@", 5],
["Shaman Karnov", "@", 5],
["Robert the Lifer", "@", 15],
["Earendil", "@", 5],
["Elwing", "@", 5],
["Hippocrates", "@", 5],
["King Arthur", "@", 5],
["Grand Master", "@", 0],
["Arch Priest", "@", 15],
["Orion", "@", 5],
["Master of Thieves", "@", 5],
["Lord Sato", "@", 5],
["Twoflower", "@", 15],
["Norn", "@", 5],
["Neferet the Green", "@", 2],
["Schliemann", "@", 5],
["Thoth Amon", "@", 5],
["Tiamat", "D", 5],
["Warden Arianna", "@", 5],
["Goblin King", "o", 5],
["Cyclops", "H", 7],
["Ixoth", "D", 1],
["Master Kaen", "@", 5],
["Nalzok", "&", 9],
["Scorpius", "s", 5],
["Master Assassin", "@", 5],
["Ashikaga Takauji", "@", 5],
["Lord Surtur", "H", 5],
["Anaraxis the Black", "@", 0],
["student", "@", 15],
["chieftain", "@", 15],
["neanderthal", "@", 15],
["inmate", "@", 0],
["High-elf", "@", 15],
["attendant", "@", 15],
["page", "@", 15],
["abbot", "@", 15],
["acolyte", "@", 15],
["hunter", "@", 15],
["thug", "@", 15],
["ninja", "@", 15],
["roshi", "@", 15],
["guide", "@", 15],
["warrior", "@", 15],
["apprentice", "@", 15],
["Punisher", "`", 0],
["dungeon fern", "F", 10],
["dungeon fern sprout", "F", 10],
["dungeon fern spore", "e", 2],
["arctic fern", "F", 12],
["arctic fern sprout", "F", 12],
["arctic fern spore", "e", 4],
["blazing fern", "F", 9],
["blazing fern sprout", "F", 9],
["blazing fern spore", "e", 1],
["swamp fern", "F", 6],
["swamp fern sprout", "F", 6],
["swamp fern spore", "e", 11],
["fern spore", "e", 3],
["Devil's Snare", "X", 2],
["Durin's Bane", "&", 1],
["Watcher in the Water", ";", 5]];

// A short name for each monster class, for the gallery picker.
export const CLASSES={"a":"ants and insects","b":"blobs","c":"cockatrices","d":"dogs","e":"floating eyes and spheres","f":"cats","g":"gnomes and gremlins","h":"dwarves and humanoids","i":"imps","j":"jellies","k":"kobolds","l":"leprechaun","m":"mimics","n":"nymphs","o":"orcs","p":"piercers","q":"quadrupeds","r":"rats","s":"spiders","t":"trappers","u":"horses","v":"vortices","w":"worms","x":"grid bugs and xan","y":"lights","z":"zruty","A":"angels","B":"bats and birds","C":"centaurs","D":"dragons","E":"elementals","F":"fungi","G":"gnomes","H":"giants","J":"jabberwock","K":"Kops","L":"liches","M":"mummies","N":"nagas","O":"ogres","P":"puddings","Q":"quantum mechanic","R":"rust monsters","S":"snakes","T":"trolls","U":"umber hulks","V":"vampires","W":"wraiths","X":"xorn","Y":"apes","Z":"zombies","'":"golems","@":"humans and elves"," ":"ghosts","&":"demons",";":"sea monsters",":":"lizards","~":"worm tail","`":"oddities"};
